version: "3"
services:
    shinobi:
      #   image: shinobi-image:1.1
        build: . 
        container_name: Shinobi
        environment:
           - PLUGIN_KEYS={"Tensorflow":"275f20d5b186421deb377c88bb826"}
           - SSL_ENABLED=false
        volumes:
           - /home/ubuntu/Shinobi/config:/config
           - /home/ubuntu/Shinobi/customAutoLoad:/home/Shinobi/libs/customAutoLoad
           - /home/ubuntu/Shinobi/database:/var/lib/mysql
           - /home/ubuntu/Shinobi/videos:/home/Shinobi/videos
           - /home/ubuntu/Shinobi/plugins:/home/Shinobi/plugins
           - /dev/shm/Shinobi/streams:/dev/shm/streams
           - /etc/localtime:/etc/localtime:ro
           - /home/ubuntu/Shinobi/web/libs/img:/home/Shinobi/web/libs/img
        ports:
           - 8080:8080
        restart: unless-stopped

    shinobiplugintensorflow:
        image: shinobisystems/shinobi-tensorflow:latest
        container_name: shinobi-tensorflow
        environment:
          - PLUGIN_KEY=275f20d5b186421deb377c88bb826
          - PLUGIN_HOST=Shinobi
        volumes:
          - /home/ubuntu/Shinobi/docker-plugins/tensorflow:/config
        restart: unless-stopped
